Repository MeshAddicts/meshinfo, pull requests merged in 2024-07, with the labels that each got.

#20 Dynamic Config
  .gitignore
  config.json.sample
  config.py
  main.py
Labels: enhancement

#22 Map & chat updates for React SPA
  frontend/.yarn/install-state.gz
  frontend/index.html
  frontend/package.json
  frontend/public/images/icons/chat.svg
  frontend/public/images/icons/map.svg
  frontend/public/images/icons/neighbors.svg
  frontend/public/images/icons/node.svg
  frontend/public/images/icons/route.svg
  frontend/public/images/icons/route2.svg
  frontend/public/images/icons/stats.svg
  frontend/public/images/icons/telemetry.svg
  frontend/src/pages/Chat.tsx
  frontend/src/pages/Map.tsx
  frontend/src/pages/Nodes.tsx
  frontend/src/router.tsx
  frontend/src/slices/apiSlice.ts
  frontend/src/types.ts
  frontend/src/utils/getDistanceBetweenPoints.ts
  frontend/yarn.lock
Labels: enhancement

#29 Refactor 20240708
  .gitignore
  Caddyfile.dev
  README.md
  config.json.sample
  data_renderer.py
  docker-compose-dev.yml
  encoders.py
  main.py
  memory_data_store.py
  models/node.py
  mqtt.py
  public/images/icons/current.svg
  public/images/icons/pressure.svg
  public/images/icons/relative-humidity.svg
  public/images/icons/resistance.svg
  static_html_renderer.py
  templates/static/chat.html.j2
  templates/static/layout.html.j2
  templates/static/map.html.j2
  templates/static/neighbors.html.j2
  templates/static/node.html.j2
  templates/static/nodes.html.j2
  templates/static/stats.html.j2
  templates/static/telemetry.html.j2
  templates/static/traceroutes.html.j2
  utils.py
Labels: enhancement

#31 MQTT Protobuf Support
  _meshtastic.py
  mosquitto/config/mosquitto.conf
  mqtt.py
  requirements.txt
  static_html_renderer.py
  templates/static/telemetry.html.j2
Labels: enhancement

#33 20240710 aiomqtt
  api/api.py
  main.py
  mqtt.py
  requirements.txt
Labels: enhancement

#24 envs in the Dockerfile persist in the container and override config.json
  Dockerfile
Labels: bug

#36 20240710 api endpoints for nodes and node
  api/api.py
Labels: enhancement

#41 Make MemoryDataStore.save async.
  data_renderer.py
  memory_data_store.py
  requirements.txt
  static_html_renderer.py
Labels: bug, enhancement

#44 Support more channels in the Chat page
  .dockerignore
  config.json.sample
  templates/static/chat.html.j2
  templates/static/stats.html.j2
Labels: enhancement

#45 20240715 Backups
  config.json.sample
  main.py
  memory_data_store.py
Labels: enhancement

#46 Add support for using encryption keys defined in config.json
  memory_data_store.py
  mqtt.py
Labels: enhancement

#49 20240716 Discord Bot
  bot/cogs/main_commands.py
  bot/discord.py
  config.json.sample
  main.py
Labels: enhancement

#51 Only print some messages if debugging is enabled
  mqtt.py
Labels: enhancement
